# Generated by Django 5.2.7 on 2026-08-01 15:39

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('scope', models.CharField(default='all', max_length=16)),
                ('document_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('citation_mode', models.CharField(default='explicit', max_length=16)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('model_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True)),
                ('is_partial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
    ]
