# Generated by Django 5.2.7 on 2026-08-01 15:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('detected_doc_type', models.CharField(blank=True, max_length=64)),
                ('proposed_fields', models.JSONField(blank=True, default=list)),
                ('accepted_fields', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_plan', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('doc_type', models.CharField(blank=True, db_index=True, max_length=48)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('title_translit', models.CharField(blank=True, max_length=1024)),
                ('primary_language', models.CharField(blank=True, db_index=True, max_length=8)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, size=None)),
                ('summary_short', models.TextField(blank=True)),
                ('summary_long', models.TextField(blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=96), blank=True, default=list, size=None)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=96), blank=True, default=list, size=None)),
                ('document_date', models.DateField(blank=True, db_index=True, null=True)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('dates', models.JSONField(blank=True, default=dict)),
                ('identifiers', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('quality_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), blank=True, default=list, size=None)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('core', models.JSONField(blank=True, default=dict)),
                ('model_id', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.CharField(default='v1', max_length=24)),
                ('validation_attempts', models.IntegerField(default=1)),
                ('is_partial', models.BooleanField(default=False)),
                ('raw_llm_output', models.TextField(blank=True)),
                ('human_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='documents.document')),
            ],
        ),
    ]
