# Generated by Django 5.2.7 on 2026-08-01 15:39

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('storage_path', models.CharField(max_length=1024)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('is_digital_pdf', models.BooleanField(null=True)),
                ('digital_text_report', models.JSONField(blank=True, default=dict)),
                ('detected_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, size=None)),
                ('status', models.CharField(db_index=True, default='uploaded', max_length=32)),
                ('status_detail', models.CharField(blank=True, max_length=512)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('metadata_mode', models.CharField(default='auto', max_length=16)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=48)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('actor', models.CharField(default='system', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.document')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('width_px', models.IntegerField(default=0)),
                ('height_px', models.IntegerField(default=0)),
                ('raster_paths', models.JSONField(blank=True, default=dict)),
                ('thumbnail_path', models.CharField(blank=True, max_length=1024)),
                ('native_text', models.TextField(blank=True)),
                ('native_char_count', models.IntegerField(default=0)),
                ('rotation_deg', models.FloatField(default=0.0)),
                ('skew_deg', models.FloatField(default=0.0)),
                ('preprocess_meta', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='TextRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.IntegerField()),
                ('source', models.CharField(choices=[('ocr_pick', 'OCR selection'), ('manual_edit', 'Manual edit'), ('ai_correction', 'AI correction'), ('manual_entry', 'Typed by hand'), ('merge', 'Merged')], max_length=24)),
                ('text', models.TextField(blank=True)),
                ('char_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('diff_stats', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('created_by', models.CharField(default='user', max_length=16)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document')),
            ],
            options={
                'ordering': ['revision_no'],
            },
        ),
    ]
