# Generated by Django 5.2.7 on 2026-08-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textrevision',
            name='origin_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='ocr.ocrrun'),
        ),
        migrations.AddField(
            model_name='textrevision',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.textrevision'),
        ),
        migrations.AddField(
            model_name='document',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.textrevision'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['document', 'seq'], name='documents_d_documen_74494e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together={('document', 'page_number')},
        ),
        migrations.AlterUniqueTogether(
            name='textrevision',
            unique_together={('document', 'revision_no')},
        ),
    ]
