# Generated by Django 5.2.17 on 2026-10-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textrevision',
            name='source',
            field=models.CharField(choices=[('ocr_pick', 'OCR selection'), ('manual_edit', 'Manual edit'), ('ai_correction', 'AI correction'), ('manual_entry', 'Typed by hand'), ('merge', 'Merged'), ('sheet_import', 'Spreadsheet import')], max_length=24),
        ),
    ]
