# Generated by Django 5.2.7 on 2026-08-01 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICorrectionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_id', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.CharField(default='v1', max_length=24)),
                ('multimodal', models.BooleanField(default=True)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('scope', models.CharField(default='all', max_length=16)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('rejected', models.JSONField(blank=True, default=list)),
                ('guard_report', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
