# Generated by Django 5.2.7 on 2026-08-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correction', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicorrectionjob',
            name='base_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.textrevision'),
        ),
        migrations.AddField(
            model_name='aicorrectionjob',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_jobs', to='documents.document'),
        ),
        migrations.AddField(
            model_name='aicorrectionjob',
            name='result_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.textrevision'),
        ),
    ]
