# Generated by Django 5.2.7 on 2026-08-01 15:39

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_model', models.CharField(max_length=64)),
                ('dims', models.IntegerField(default=1024)),
                ('chunk_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_runs', to='documents.document')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.textrevision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('page_start', models.IntegerField(blank=True, null=True)),
                ('page_end', models.IntegerField(blank=True, null=True)),
                ('section_path', models.TextField(blank=True, default='')),
                ('lang', models.CharField(default='mixed', max_length=8)),
                ('text', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('char_count', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.textrevision')),
            ],
            options={
                'db_table': 'rag_chunk',
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='rag_chunk_documen_f18433_idx'), pgvector.django.indexes.HnswIndex(ef_construction=200, fields=['embedding'], m=16, name='chunk_hnsw', opclasses=['vector_cosine_ops'])],
                'unique_together': {('revision', 'chunk_index')},
            },
        ),
    ]
