# Generated by Django 5.2.17 on 2026-10-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_alter_textrevision_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=64)),
                ('header_row', models.IntegerField(blank=True, null=True)),
                ('header_rows', models.IntegerField(default=1)),
                ('row_count', models.IntegerField(default=0)),
                ('col_count', models.IntegerField(default=0)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('profile', models.JSONField(blank=True, default=list)),
                ('proposed_schema', models.JSONField(blank=True, default=dict)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('schema_status', models.CharField(default='pending', max_length=16)),
                ('schema_source', models.CharField(blank=True, max_length=16)),
                ('proposal_error', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='documents.document')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('document', 'index')},
            },
        ),
    ]
