# Generated by Django 5.2.7 on 2026-08-01 15:39

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(db_index=True, max_length=48)),
                ('available', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('detail', models.CharField(blank=True, max_length=512)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_engines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), default=list, size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, size=None)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('celery_group_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_batches', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_name', models.CharField(db_index=True, max_length=48)),
                ('engine_version', models.CharField(blank=True, max_length=64)),
                ('model_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('preprocess_profile', models.CharField(blank=True, max_length=24)),
                ('dpi', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('mean_confidence', models.FloatField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('char_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('arabic_char_ratio', models.FloatField(blank=True, null=True)),
                ('gibberish_score', models.FloatField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ocr.ocrbatch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_runs', to='documents.document')),
            ],
            options={
                'ordering': ['engine_name'],
                'unique_together': {('batch', 'engine_name')},
            },
        ),
        migrations.CreateModel(
            name='OCRPageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_results', to='ocr.ocrrun')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('run', 'page_number')},
            },
        ),
    ]
